trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates # alias you choose
      type: git
      name: pipeline-templates
      # Pin to a tag/branch for reproducibility, e.g. refs/tags/v1.2.3
      ref: refs/tags/latest

variables:
  - group: vg-CopierTest

parameters:
  - name: project
    displayName: Project Name
    type: string
    default: dns
    values: ["dns"]
  - name: serviceConnection
    displayName: Azure service connection
    type: string
    default: infrastructure-service-connection
    values: ["infrastructure-service-connection"]
  - name: environments
    displayName: Target environment (maps to tfvars)
    type: object
    default:

      - name: dev
        slotVariable: ""


      - name: qa
        slotVariable: ""


      - name: prod
        slotVariable: ""

      - name: dr-prod
        slotVariable: DR_SLOT_PROD


  - name: tfVersion
    displayName: Terraform version
    type: string
    default: "1.6.6"
  - name: workingDir
    displayName: Terraform working directory
    type: string
    default: terraform
    values: ["terraform"]

pool: $[coalesce(variables.VG_DEFAULT_RUNNER, 'Azure Pipelines')]

stages:
  ### PR PIPELINE
  - ${{ if eq(variables['Build.Reason'], 'PullRequest')}}:
      - ${{ each env in parameters.environments}}:
          - template: templates/v1/stages/terraform-plan.yml@templates
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              tfVersion: ${{ parameters.tfVersion }}
              workingDir: ${{ parameters.workingDir }}
              ${{ if ne(env.slotVariable, '' ) }}:
                tfVarsFile: ${{ parameters.workingDir}}/environments/${{ env.name}}.$(${{ env.slotVariable }}).tfvars
              ${{ if eq(env.slotVariable, '' ) }}:
                tfVarsFile: ${{ parameters.workingDir}}/environments/${{ env.name}}.tfvars
              stageName: Validate_Plan_${{ replace(env.name, '-', '_') }}
              displayName: Validate & Plan ${{ env.name }}

  ### MAIN PIPELINE
  - ${{ if ne(variables['Build.Reason'], 'PullRequest')}}:
      - ${{ each env in parameters.environments}}:
          - template: templates/v1/stages/terraform-plan.yml@templates
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              tfVersion: ${{ parameters.tfVersion }}
              workingDir: ${{ parameters.workingDir }}
              ${{ if ne(env.slotVariable, '' ) }}:
                tfVarsFile: ${{ parameters.workingDir}}/environments/${{ env.name}}.$(${{ env.slotVariable }}).tfvars
              ${{ if eq(env.slotVariable, '' ) }}:
                tfVarsFile: ${{ parameters.workingDir}}/environments/${{ env.name}}.tfvars
              stageName: Validate_Plan_${{ replace(env.name, '-', '_') }}
              displayName: Validate & Plan ${{ env.name }}

          - template: templates/v1/stages/terraform-apply.yml@templates
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              workingDir: ${{ parameters.workingDir }}
              environmentName: ${{ format('{0}-terraform-{1}', parameters.project ,env.name) }}
              dependsOn: Validate_Plan_${{ replace(env.name, '-', '_') }}
              stageName: Apply_${{ replace(env.name, '-', '_') }}
              displayName: Apply ${{ env.name }}
